More fixes
Signed-off-by: Flavius Lacatusu <flacatus@redhat.com>

diff --git a/.github/workflows/readme-update.yml b/.github/workflows/readme-update.yml
--- a/.github/workflows/readme-update.yml
+++ b/.github/workflows/readme-update.yml
@@ -1,9 +1,9 @@
-name: Lint source code
+name: Chectl
 on: [pull_request]
 
 jobs:
   run:
-    name: Check readme
+    name: Automation checks
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repo
@@ -14,9 +14,12 @@ jobs:
           node-version: 12.x
       - name: Pack chectl
         run: yarn pack
-      - name: Commit Readme changes to the PR
-        uses: EndBug/add-and-commit@v6
-        with:
-          add: 'README.md'
-          cwd: go/src/github.com/che-incubator/${{ github.repository }}
-          message: "Update Readme"
+      - name: Check README.md state
+        run: |
+          IFS=$'\n' read -d '' -r -a FILES_CHANGED_ARRAY < <( git ls-files -m ) || true
+          # check if readme it is updated
+          if [[ " ${FILES_CHANGED_ARRAY[@]} " =~ "README.md" ]]; then
+            echo "[ERROR] README.md it is not updated. Please run yarn pack to update and commit the changes."
+            exit 1
+          fi
+
